version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitcity
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]

  api:
    build:
      context: ../
      dockerfile: ./infra/docker/api.Dockerfile
    env_file: ../internal/config/env.example
    depends_on: [db, minio]
    ports: ["8080:8080"]

volumes:
  pgdata:
  minio: