version: "3.9"
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./env/db.env
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  minio:
    image: minio/minio
    env_file:
      - ./env/minio.env
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports: ["1025:1025","8025:8025"]

  api:
    build:
      context: ../
      dockerfile: ./infra/docker/api.Dockerfile
    env_file: ./env/api.local.env
    depends_on: [db, minio, mailhog]
    ports: ["8080:8080"]

volumes:
  pgdata:
  minio:
